### ISSUE TITLE
ambiguous bevaiour in case of input jsons with duplicate edges

### ISSUE THREAD

**Issue by parence** [cassinius/graphinius#31]
Inputs from JSONS with duplicate undirected edges can produce ambiguous behaviour!

In a JSON it is possible to have two undirected edges (duplicates) {a,b} and {b,a}. The current implementation manages this by checking if {a,b} or {b,a} already exists in the graph and subsequently skips the edge if the above statement is true. However, this can produce ambiguous behaviour if the weights of the duplicates do not match (we do not know which edge will be kept and which one rejected)! 

Solution: Consider this kind of inputs as flawed and throw an error!

small_graph.json is such a flawed graph (weight(A_B_u) != weight(B_A_u))

**Comment by cassinius** [comment]
needs new examination now as we're re-designing node / edge type system

**Comment by cassinius** [comment]
since edges in TypedGraph can henceforth have different types even if their nodes & weights are the same (e.g. `friendship` & `co-authors`), we can either
- introduce more complex checks
- leave the responsibility for meaningful relations (:-P) to the programmer

Still thinking about it but I guess we should go with the latter.

**Comment by cassinius** [comment]
From the NetworkX documentation:

"The density is 0 for a graph without edges and 1 for a complete graph. The density of multigraphs can be higher than 1.

Self loops are counted in the total number of edges so graphs with self loops can have density higher than 1."

**Comment by cassinius** [comment]
DONE -> wrote Dupes checker class according to extremely intricate BDD ;-)
